import { Injectable } from '@angular/core';
import { Observable, of } from 'rxjs';
import { InvoiceData } from '../model/invoice.model';

@Injectable({
  providedIn: 'root'
})
export class InvoiceService {

  private mockData: InvoiceData ={
    "invoice": {
        "invoice_number": "291",
        "invoice_date": "01/05/25",
        "irn_number": "f5eaba8ba61e2dcb566111065b655f147705e35e47289454bef3878eebb8ebe4e",
        "acknowledgement_no": "",
        "acknowledgement_data": "",
        "e_way_bill_no": "201953632779"
    },
    "supplier": {
        "suplier_name": "ZEAL APPAREL",
        "supplier_address": "234, ASHISH INDUSTRIAL ESTATE, GOKHALE ROAD (SOUTH), DADAR(WEST), MUMBAI MAHARASHTRA(27)",
        "supplier_gst_no": "27AALPI1722H1ZM",
        "msme_no": "",
        "pan_no": ""
    },
    "purchase": {
        "order_no": "",
        "order_date": "",
        "transport_name": "TAMILNADU SUPER SERV",
        "agent_name": "PAREKH ASSOCIATES",
        "LR_no": "PAREKH ASSOCIATES",
        "LR_date": "",
        "merchandiser_name": ""
    },
    "taxes": {
        "taxable_value": "",
        "CGST_amount": "",
        "SGST_amount": "",
        "IGST_amount": "10890.00",
        "total_tax_amount": "90750.00"
    },
    "discount": {
        "discount_percentage": "",
        "discount_amount": ""
    },
    "charges": {
        "other_deductions": "",
        "freight_charges": "",
        "other_charges": ""
    },
    "amount": {
        "round_off_amount": "",
        "invoice_amount": "90750.00",
        "amount_in_words": "Rupees One Lacs One Thousand Six Hundred Forty Only"
    },
    "billing": {
        "billed_to": "",
        "bank_name": "THE FEDERAL BANK LTD",
        "bank_branch": "DADAR EAST",
        "account_name": "",
        "account_no": "11995500001126",
        "IFSC_code": "FDRL0001199"
    },
    "product_details": {
        "items": [
            {
                "s_no": 1,
                "category": "",
                "description": "CS-4077-CS/3PC",
                "design_code": "CS-4077-CS/3PC",
                "size": "1",
                "color": "",
                "UOM": "",
                "pieces": "",
                "quantity": "3",
                "rate": "2700",
                "MRP_rate": "4725",
                "item_discount_percentage": "",
                "item_discount_amount": "",
                "product_valued": "",
                "HSN": "610310",
                "tax_percentage": "12.00",
                "tax_amount": "10890.00"
            },
            {
                "s_no": 2,
                "category": "",
                "description": "CS-4077-CS/3PC",
                "design_code": "CS-4077-CS/3PC",
                "size": "2",
                "color": "",
                "UOM": "",
                "pieces": "",
                "quantity": "3",
                "rate": "2750",
                "MRP_rate": "4815",
                "item_discount_percentage": "",
                "item_discount_amount": "",
                "product_valued": "",
                "HSN": "610310",
                "tax_percentage": "12.00",
                "tax_amount": "10890.00"
            },
            {
                "s_no": 3,
                "category": "",
                "description": "CS-4077-CS/3PC",
                "design_code": "CS-4077-CS/3PC",
                "size": "3",
                "color": "",
                "UOM": "",
                "pieces": "",
                "quantity": "3",
                "rate": "2800",
                "MRP_rate": "4900",
                "item_discount_percentage": "",
                "item_discount_amount": "",
                "product_valued": "",
                "HSN": "610310",
                "tax_percentage": "12.00",
                "tax_amount": "10890.00"
            },
            {
                "s_no": 4,
                "category": "",
                "description": "CS-4077-CS/3PC",
                "design_code": "CS-4077-CS/3PC",
                "size": "4",
                "color": "",
                "UOM": "",
                "pieces": "",
                "quantity": "3",
                "rate": "2850",
                "MRP_rate": "4990",
                "item_discount_percentage": "",
                "item_discount_amount": "",
                "product_valued": "",
                "HSN": "610310",
                "tax_percentage": "12.00",
                "tax_amount": "10890.00"
            },
            {
                "s_no": 5,
                "category": "",
                "description": "CS-4077-CS/3PC",
                "design_code": "CS-4077-CS/3PC",
                "size": "5",
                "color": "",
                "UOM": "",
                "pieces": "",
                "quantity": "3",
                "rate": "2900",
                "MRP_rate": "5075",
                "item_discount_percentage": "",
                "item_discount_amount": "",
                "product_valued": "",
                "HSN": "610310",
                "tax_percentage": "12.00",
                "tax_amount": "10890.00"
            },
            {
                "s_no": 6,
                "category": "",
                "description": "CS-4077-CS/3PC",
                "design_code": "CS-4077-CS/3PC",
                "size": "6",
                "color": "",
                "UOM": "",
                "pieces": "",
                "quantity": "3",
                "rate": "2250",
                "MRP_rate": "5690",
                "item_discount_percentage": "",
                "item_discount_amount": "",
                "product_valued": "",
                "HSN": "610310",
                "tax_percentage": "12.00",
                "tax_amount": "10890.00"
            },
            {
                "s_no": 7,
                "category": "",
                "description": "CS-4077-CS/3PC",
                "design_code": "CS-4077-CS/3PC",
                "size": "8",
                "color": "",
                "UOM": "",
                "pieces": "",
                "quantity": "3",
                "rate": "3350",
                "MRP_rate": "5865",
                "item_discount_percentage": "",
                "item_discount_amount": "",
                "product_valued": "",
                "HSN": "610310",
                "tax_percentage": "12.00",
                "tax_amount": "10890.00"
            },
            {
                "s_no": 8,
                "category": "",
                "description": "CS-4077-CS/3PC",
                "design_code": "CS-4077-CS/3PC",
                "size": "10",
                "color": "",
                "UOM": "",
                "pieces": "",
                "quantity": "3",
                "rate": "3450",
                "MRP_rate": "6040",
                "item_discount_percentage": "",
                "item_discount_amount": "",
                "product_valued": "",
                "HSN": "610310",
                "tax_percentage": "12.00",
                "tax_amount": "10890.00"
            },
            {
                "s_no": 9,
                "category": "",
                "description": "CS-4077-CS/3PC",
                "design_code": "CS-4077-CS/3PC",
                "size": "12",
                "color": "",
                "UOM": "",
                "pieces": "",
                "quantity": "3",
                "rate": "3550",
                "MRP_rate": "6215",
                "item_discount_percentage": "",
                "item_discount_amount": "",
                "product_valued": "",
                "HSN": "610310",
                "tax_percentage": "12.00",
                "tax_amount": "10890.00"
            },
            {
                "s_no": 10,
                "category": "",
                "description": "CS-4077-CS/3PC",
                "design_code": "CS-4077-CS/3PC",
                "size": "14",
                "color": "",
                "UOM": "",
                "pieces": "",
                "quantity": "3",
                "rate": "",
                "MRP_rate": "",
                "item_discount_percentage": "",
                "item_discount_amount": "",
                "product_valued": "",
                "HSN": "610310",
                "tax_percentage": "12.00",
                "tax_amount": "10890.00"
            },
            {
                "s_no": 11,
                "category": "",
                "description": "CS-4077-CS/3PC",
                "design_code": "CS-4077-CS/3PC",
                "size": "16",
                "color": "",
                "UOM": "",
                "pieces": "",
                "quantity": "3",
                "rate": "",
                "MRP_rate": "",
                "item_discount_percentage": "",
                "item_discount_amount": "",
                "product_valued": "",
                "HSN": "610310",
                "tax_percentage": "12.00",
                "tax_amount": "10890.00"
            },
            {
                "s_no": 12,
                "category": "",
                "description": "CS-4077-CS/3PC",
                "design_code": "CS-4077-CS/3PC",
                "size": "7",
                "color": "",
                "UOM": "",
                "pieces": "",
                "quantity": "",
                "rate": "",
                "MRP_rate": "",
                "item_discount_percentage": "",
                "item_discount_amount": "",
                "product_valued": "",
                "HSN": "610310",
                "tax_percentage": "12.00",
                "tax_amount": "10890.00"
            },
            {
                "s_no": 13,
                "category": "",
                "description": "CS-4077-CS/3PC",
                "design_code": "CS-4077-CS/3PC",
                "size": "9",
                "color": "",
                "UOM": "",
                "pieces": "",
                "quantity": "",
                "rate": "",
                "MRP_rate": "",
                "item_discount_percentage": "",
                "item_discount_amount": "",
                "product_valued": "",
                "HSN": "610310",
                "tax_percentage": "12.00",
                "tax_amount": "10890.00"
            },
            {
                "s_no": 14,
                "category": "",
                "description": "CS-4077-CS/3PC",
                "design_code": "CS-4077-CS/3PC",
                "size": "11",
                "color": "",
                "UOM": "",
                "pieces": "",
                "quantity": "",
                "rate": "",
                "MRP_rate": "",
                "item_discount_percentage": "",
                "item_discount_amount": "",
                "product_valued": "",
                "HSN": "610310",
                "tax_percentage": "12.00",
                "tax_amount": "10890.00"
            },
            {
                "s_no": 15,
                "category": "",
                "description": "CS-4077-CS/3PC",
                "design_code": "CS-4077-CS/3PC",
                "size": "00",
                "color": "",
                "UOM": "",
                "pieces": "",
                "quantity": "",
                "rate": "",
                "MRP_rate": "",
                "item_discount_percentage": "",
                "item_discount_amount": "",
                "product_valued": "",
                "HSN": "610310",
                "tax_percentage": "12.00",
                "tax_amount": "10890.00"
            },
            {
                "s_no": 1,
                "category": "",
                "description": "CS-4078-CS/3PC",
                "design_code": "CS-4078-CS/3PC",
                "size": "0",
                "color": "",
                "UOM": "",
                "pieces": "",
                "quantity": "3",
                "rate": "2650",
                "MRP_rate": "4640",
                "item_discount_percentage": "",
                "item_discount_amount": "",
                "product_valued": "",
                "HSN": "610310",
                "tax_percentage": "12.00",
                "tax_amount": "90750.00"
            },
            {
                "s_no": 2,
                "category": "",
                "description": "CS-4078-CS/3PC",
                "design_code": "CS-4078-CS/3PC",
                "size": "1",
                "color": "",
                "UOM": "",
                "pieces": "",
                "quantity": "3",
                "rate": "2700",
                "MRP_rate": "4725",
                "item_discount_percentage": "",
                "item_discount_amount": "",
                "product_valued": "",
                "HSN": "610310",
                "tax_percentage": "12.00",
                "tax_amount": "90750.00"
            },
            {
                "s_no": 3,
                "category": "",
                "description": "CS-4078-CS/3PC",
                "design_code": "CS-4078-CS/3PC",
                "size": "2",
                "color": "",
                "UOM": "",
                "pieces": "",
                "quantity": "3",
                "rate": "2750",
                "MRP_rate": "4815",
                "item_discount_percentage": "",
                "item_discount_amount": "",
                "product_valued": "",
                "HSN": "610310",
                "tax_percentage": "12.00",
                "tax_amount": "90750.00"
            },
            {
                "s_no": 4,
                "category": "",
                "description": "CS-4078-CS/3PC",
                "design_code": "CS-4078-CS/3PC",
                "size": "3",
                "color": "",
                "UOM": "",
                "pieces": "",
                "quantity": "3",
                "rate": "2800",
                "MRP_rate": "4900",
                "item_discount_percentage": "",
                "item_discount_amount": "",
                "product_valued": "",
                "HSN": "610310",
                "tax_percentage": "12.00",
                "tax_amount": "90750.00"
            },
            {
                "s_no": 5,
                "category": "",
                "description": "CS-4078-CS/3PC",
                "design_code": "CS-4078-CS/3PC",
                "size": "4",
                "color": "",
                "UOM": "",
                "pieces": "",
                "quantity": "3",
                "rate": "2850",
                "MRP_rate": "4990",
                "item_discount_percentage": "",
                "item_discount_amount": "",
                "product_valued": "",
                "HSN": "610310",
                "tax_percentage": "12.00",
                "tax_amount": "90750.00"
            },
            {
                "s_no": 6,
                "category": "",
                "description": "CS-4078-CS/3PC",
                "design_code": "CS-4078-CS/3PC",
                "size": "5",
                "color": "",
                "UOM": "",
                "pieces": "",
                "quantity": "3",
                "rate": "2900",
                "MRP_rate": "5075",
                "item_discount_percentage": "",
                "item_discount_amount": "",
                "product_valued": "",
                "HSN": "610310",
                "tax_percentage": "12.00",
                "tax_amount": "90750.00"
            },
            {
                "s_no": 7,
                "category": "",
                "description": "CS-4078-CS/3PC",
                "design_code": "CS-4078-CS/3PC",
                "size": "6",
                "color": "",
                "UOM": "",
                "pieces": "",
                "quantity": "3",
                "rate": "2250",
                "MRP_rate": "5690",
                "item_discount_percentage": "",
                "item_discount_amount": "",
                "product_valued": "",
                "HSN": "610310",
                "tax_percentage": "12.00",
                "tax_amount": "90750.00"
            },
            {
                "s_no": 8,
                "category": "",
                "description": "CS-4078-CS/3PC",
                "design_code": "CS-4078-CS/3PC",
                "size": "8",
                "color": "",
                "UOM": "",
                "pieces": "",
                "quantity": "3",
                "rate": "3350",
                "MRP_rate": "5865",
                "item_discount_percentage": "",
                "item_discount_amount": "",
                "product_valued": "",
                "HSN": "610310",
                "tax_percentage": "12.00",
                "tax_amount": "90750.00"
            },
            {
                "s_no": 9,
                "category": "",
                "description": "CS-4078-CS/3PC",
                "design_code": "CS-4078-CS/3PC",
                "size": "10",
                "color": "",
                "UOM": "",
                "pieces": "",
                "quantity": "3",
                "rate": "3450",
                "MRP_rate": "6040",
                "item_discount_percentage": "",
                "item_discount_amount": "",
                "product_valued": "",
                "HSN": "610310",
                "tax_percentage": "12.00",
                "tax_amount": "90750.00"
            },
            {
                "s_no": 10,
                "category": "",
                "description": "CS-4078-CS/3PC",
                "design_code": "CS-4078-CS/3PC",
                "size": "12",
                "color": "",
                "UOM": "",
                "pieces": "",
                "quantity": "3",
                "rate": "3550",
                "MRP_rate": "6215",
                "item_discount_percentage": "",
                "item_discount_amount": "",
                "product_valued": "",
                "HSN": "610310",
                "tax_percentage": "12.00",
                "tax_amount": "90750.00"
            },
            {
                "s_no": 11,
                "category": "",
                "description": "CS-4078-CS/3PC",
                "design_code": "CS-4078-CS/3PC",
                "size": "14",
                "color": "",
                "UOM": "",
                "pieces": "",
                "quantity": "3",
                "rate": "",
                "MRP_rate": "",
                "item_discount_percentage": "",
                "item_discount_amount": "",
                "product_valued": "",
                "HSN": "610310",
                "tax_percentage": "12.00",
                "tax_amount": "90750.00"
            },
            {
                "s_no": 12,
                "category": "",
                "description": "CS-4078-CS/3PC",
                "design_code": "CS-4078-CS/3PC",
                "size": "16",
                "color": "",
                "UOM": "",
                "pieces": "",
                "quantity": "3",
                "rate": "",
                "MRP_rate": "",
                "item_discount_percentage": "",
                "item_discount_amount": "",
                "product_valued": "",
                "HSN": "610310",
                "tax_percentage": "12.00",
                "tax_amount": "90750.00"
            },
            {
                "s_no": 13,
                "category": "",
                "description": "CS-4078-CS/3PC",
                "design_code": "CS-4078-CS/3PC",
                "size": "7",
                "color": "",
                "UOM": "",
                "pieces": "",
                "quantity": "",
                "rate": "",
                "MRP_rate": "",
                "item_discount_percentage": "",
                "item_discount_amount": "",
                "product_valued": "",
                "HSN": "610310",
                "tax_percentage": "12.00",
                "tax_amount": "90750.00"
            },
            {
                "s_no": 14,
                "category": "",
                "description": "CS-4078-CS/3PC",
                "design_code": "CS-4078-CS/3PC",
                "size": "9",
                "color": "",
                "UOM": "",
                "pieces": "",
                "quantity": "",
                "rate": "",
                "MRP_rate": "",
                "item_discount_percentage": "",
                "item_discount_amount": "",
                "product_valued": "",
                "HSN": "610310",
                "tax_percentage": "12.00",
                "tax_amount": "90750.00"
            },
            {
                "s_no": 15,
                "category": "",
                "description": "CS-4078-CS/3PC",
                "design_code": "CS-4078-CS/3PC",
                "size": "11",
                "color": "",
                "UOM": "",
                "pieces": "",
                "quantity": "",
                "rate": "",
                "MRP_rate": "",
                "item_discount_percentage": "",
                "item_discount_amount": "",
                "product_valued": "",
                "HSN": "610310",
                "tax_percentage": "12.00",
                "tax_amount": "90750.00"
            },
            {
                "s_no": 16,
                "category": "",
                "description": "CS-4078-CS/3PC",
                "design_code": "CS-4078-CS/3PC",
                "size": "00",
                "color": "",
                "UOM": "",
                "pieces": "",
                "quantity": "",
                "rate": "",
                "MRP_rate": "",
                "item_discount_percentage": "",
                "item_discount_amount": "",
                "product_valued": "",
                "HSN": "610310",
                "tax_percentage": "12.00",
                "tax_amount": "90750.00"
            }
        ],
        "total_quantity": 30,
        "total_net_Amount": 181500
    }
}

  getMockData():Observable<InvoiceData>{
    return of(this.mockData);
  }
}
